# Generated by Django 6.0.6 on 2026-06-21 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Auto-updated timestamp on every save')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete marker (null = active)', null=True)),
                ('object_id', models.BigIntegerField(help_text='Primary key of the changed object')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export')], db_index=True, help_text='What action was performed', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request that triggered this change', null=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON dict of field-level changes')),
                ('content_type', models.ForeignKey(help_text='Which model was changed (e.g., Product, Order)', on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
