# Generated by Django 6.0.6 on 2026-07-25 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Auto-updated timestamp on every save')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete marker (null = active)', null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='#7c3aed', help_text='Hex color for UI accents', max_length=7)),
                ('is_archived', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habits_habit',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HabitCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Auto-updated timestamp on every save')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete marker (null = active)', null=True)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='habits.habit')),
            ],
            options={
                'db_table': 'habits_habitcheckin',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_archived'], name='habit_user_arch_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'sort_order'], name='habit_user_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcheckin',
            index=models.Index(fields=['habit', 'date'], name='habit_checkin_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='habitcheckin',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('habit', 'date'), name='habit_checkin_unique_active'),
        ),
    ]
