# Generated by Django 6.0.6 on 2026-07-25 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Auto-updated timestamp on every save')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete marker (null = active)', null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('todo', 'To do'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('due_time', models.TimeField(blank=True, help_text='Optional time-of-day ordering within due_date', null=True)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('external_source', models.CharField(blank=True, default='', help_text='Provider key, e.g. "google"', max_length=50)),
                ('external_id', models.CharField(blank=True, default='', help_text='Remote event/task id for sync', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_task',
                'ordering': ['sort_order', 'due_time', 'id'],
                'indexes': [models.Index(fields=['user', 'due_date', 'status'], name='task_user_due_status_idx'), models.Index(fields=['user', 'status'], name='task_user_status_idx'), models.Index(fields=['user', 'starts_at'], name='task_user_starts_idx'), models.Index(fields=['user', 'external_source', 'external_id'], name='task_user_external_idx')],
            },
        ),
    ]
