# Generated by Django 6.0.6 on 2026-07-25 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Auto-updated timestamp on every save')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete marker (null = active)', null=True)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, default='#7c3aed', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='notes.notefolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes_notefolder',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Auto-updated timestamp on every save')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete marker (null = active)', null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.notefolder')),
            ],
            options={
                'db_table': 'notes_note',
                'ordering': ['-is_pinned', 'sort_order', '-updated_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='notefolder',
            index=models.Index(fields=['user', 'sort_order'], name='note_folder_user_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_archived', 'is_pinned'], name='note_user_arch_pin_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'folder'], name='note_user_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'updated_at'], name='note_user_updated_idx'),
        ),
    ]
