# Generated by Django 6.0.6 on 2026-07-26 05:41

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Auto-updated timestamp on every save')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete marker (null = active)', null=True)),
                ('token', models.CharField(db_index=True, default=users.models.generate_invite_token, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_invite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='invite_expires_at_idx'), models.Index(fields=['revoked_at'], name='invite_revoked_at_idx')],
            },
        ),
    ]
